### ISSUE TITLE
Enable lazy loading to improve website performance

### ISSUE THREAD

**Issue by M-A-N-I-K** [ssitvit/Games-and-Go#89] opened 2023-05-21 11:20 UTC
Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of images and other resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

-     Reduced initial load time
-     Improved user experience
-     More responsive website
-     Increased SEO ranking

**Comment by raj03kumar** [comment] 2023-05-21 12:06
Assigned this issue to you. Kindly complete the work within 10 days, go through the readme and contributing.md for successful merge. All the best to your work Manik... !!!

**Comment by Avinash905** [comment] 2023-06-02 20:48
@raj03kumar It's been two weeks since the issue has been assigned but the issue is not resolved. If he is not working then you can assign it to me under **GSSOC'23** so that I can start working on it.

**Comment by M-A-N-I-K** [comment] 2023-06-03 03:14
@raj03kumar i have already made a PR for this issue. Kindly please check PR'S first

**Closed** 2023-08-10 17:59 UTC
Labels: enhancement, gssoc23, level2
